// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjkptijbjyxbrgbxwgxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqa3B0aWpianl4YnJnYnh3Z3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NTUwNjYsImV4cCI6MjA3NjAzMTA2Nn0.S0zxO5aV1WQ1X4uolvNn-ssu_Ic35Rth6kVw_PxfbmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  db: {
    schema: 'public'
  },
  realtime: {
    timeout: 30000,
    heartbeatIntervalMs: 30000,
    reconnectAfterMs: (tries: number) => Math.min(tries * 1000, 30000),
  }
});

// Log apenas em desenvolvimento
if (import.meta.env.DEV) {
  console.log("🔧 [SUPABASE] Cliente configurado:", {
    url: SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    env: import.meta.env.MODE
  });
}